### ISSUE TITLE
Invalid mention in release description

### ISSUE THREAD

**Issue by ghost** [AMDmi3/qnetwalk#10]
I recently contributed in this repository and was mentioned in the [this](https://github.com/AMDmi3/qnetwalk/releases/tag/1.8.0) release description. However, I noticed that the reference used in the mention is invalid. For example, my GitHub username is @sogreatandpowerfull, but in the release description, the owner mentioned @sogreatandpowerful instead.

This could potentially cause confusion for other users who might try to reach out to me based on the mention in the release notes. I would appreciate it if you could kindly update the release description to correct the mention to my correct username (which is @sogreatandpowerfull).

Thank you.

**Comment by AMDmi3** [comment]
It looks like I've mixed up name and account name. Fixed in change log and release description.
